The branch was renamed. I did nothing with files from previous commit.
pivancy/itea-advanced-python pull request #14
Opened 2017-05-08 09:40 UTC by RomanPryima

2017-05-08 12:27 UTC, UkrainianEngineer requested changes

2017-05-08 12:27 UTC, pivancy commented on homework-2/set-tuple-dict.py
> +
Is this a part of your page?

2017-05-08 12:27 UTC, pivancy commented on travel/Html/base.html
> +	<meta charset="UTF-8">
Please use just 2 spaces in your HTML and CSS code.

2017-05-08 12:27 UTC, pivancy commented on travel/Html/base.html
> +	{% block content %}
Please fix formatting for `content` block. Something is wrong with spaces around.

2017-05-08 12:27 UTC, pivancy commented on travel/config_reader.py
> +"""
Looks like config parsed is another task. It should be merged into separate branch.

2017-05-08 13:53 UTC, Sasha1152 commented on travel/Html/main.html
> +		<span class="text-center">Retaurants</span>
missing letter "s"

2017-05-09 16:49 UTC, pivancy commented on travel/Html/css/style.css
> +	background-color: white;
wtf?

2017-05-10 18:09 UTC, RomanPryima commented on travel/config_reader.py
> +"""
Removed in local repository. Made push origin. But files are still in remote branch. Will check on the next lesson.

2017-05-10 18:09 UTC, RomanPryima commented on travel/Html/main.html
> +		<span class="text-center">Retaurants</span>
Fixed

2017-05-10 18:09 UTC, RomanPryima commented on travel/Html/base.html
> +	<meta charset="UTF-8">
Removed extra spaces.

2017-05-10 18:10 UTC, RomanPryima commented on homework-2/set-tuple-dict.py
> +
Removed

2017-05-10 18:10 UTC, RomanPryima commented on travel/Html/base.html
> +	{% block content %}
fixed

2017-05-10 18:17 UTC, RomanPryima commented on travel/config_reader.py
> +"""
Already done

2017-05-11 19:24 UTC, UkrainianEngineer commented on travel/Html/base.html
> +<meta name="description" content="Boocking system">
typo

2017-05-11 19:24 UTC, UkrainianEngineer commented on travel/Html/base.html
> +<meta name="keywords" content="Travel,travels,boocking,tickets,hotels">
typo

2017-05-11 19:24 UTC, UkrainianEngineer commented on travel/Html/css/style.css
> +	font-family: 'Acme', sans-serif;
too many spaces

2017-05-11 19:24 UTC, UkrainianEngineer commented on travel/Html/css/style.css
> +	display:inline-block;
Something happened with spaces

2017-05-11 19:24 UTC, UkrainianEngineer commented on travel/Html/css/style.css
> +    display:inline-block;
space after `:` in a lot of places

2017-05-11 19:24 UTC, UkrainianEngineer commented on travel/Html/main.html
> +	<span class="text-center">Entertaiment</span>
typo

2017-05-11 19:24 UTC, UkrainianEngineer commented on travel/Html/main.html
> +	<form action="<!---->" method="get">
what is the action here?

2017-05-11 19:24 UTC, UkrainianEngineer commented on travel/Html/main.html
> +	<div class="text-right col-md-2"><h3>I have</h3></div>
too many spaces

2017-05-11 19:24 UTC, UkrainianEngineer commented on travel/Html/travel_platform.html
> +		<meta name="description" content="Boocking system">
same typo

2017-05-11 19:24 UTC, UkrainianEngineer commented on travel/Html/travel_platform.html
> +<!DOCTYPE html>
I can't catch a difference between this file and `main.html`

2017-05-12 21:36 UTC, Sasha1152 commented on travel/Html/main.html
> +		<span class="text-center">Retaurants</span>
:+1:

2017-05-13 07:15 UTC, RomanPryima commented on travel/Html/main.html
> +	<form action="<!---->" method="get">
@pivancy  action will be defined later. Now it is awry commented

2017-05-13 07:20 UTC, RomanPryima commented on travel/Html/travel_platform.html
> +<!DOCTYPE html>
The main.html is a block for inserting into base.html in Django.
The travel_platform is full html, as it was developed.

2017-05-13 09:08 UTC, kate-ka commented on travel/Html/main.html
> +	<form action="<!---->" method="get">
I can't see no closing form tag

2017-05-13 10:04 UTC, Sasha1152 commented
:+1:

2017-05-14 08:28 UTC, pivancy commented on travel/Html/main.html
> +	<form action="<!---->" method="get">
Then it's much better to remove action at all.

2017-05-14 08:31 UTC, UkrainianEngineer requested changes

2017-05-14 08:31 UTC, pivancy commented on travel/Html/travel_platform.html
> +<!DOCTYPE html>
Well, if you're trying to implement logic with base template, you don't need to write full HTML in separate file. You just need to extend base template with some specific information.

2017-05-15 18:10 UTC, closed without merging

2017-05-15 18:12 UTC, pivancy commented
@RomanPryima why this pull request was closed?

2017-05-15 19:07 UTC, RomanPryima commented
created new branch. As we decided