ITEA-8-create-configuration-parser
pivancy/itea-advanced-python pull request #21
Opened 2017-05-16 10:43 UTC by RomanPryima

First variant of parser. Still unknown the format of data it will be using for.

2017-05-16 11:34 UTC, pivancy commented on config_parser/config_reader.py
> +def get_setting(cfg_file, section,  parameter):
too many spaces before `parameter`

2017-05-16 11:34 UTC, pivancy commented on config_parser/config_reader.py
> +    cfg_file - name or path and name of cfg file for parsing
It would be great to follow:
http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

2017-05-20 09:49 UTC, RomanPryima commented on config_parser/config_reader.py
> +    cfg_file - name or path and name of cfg file for parsing
Fixed. As I was able to understand how to.

2017-05-20 10:22 UTC, pivancy commented on config_parser/config_reader.py
> +        cfg_file - name or path and name of cfg file for parsing
It would be great to add type of variable.

2017-05-20 10:22 UTC, pivancy commented on config_parser/config_reader.py
> +        The return value. The value of requested parameter in requested
It's awesome! 😎 
`Return return value` - Captain Obvious, it's you? 😂 

Well, it should describe type of return value and reason of it.

2017-05-20 12:34 UTC, RomanPryima commented on config_parser/config_reader.py
> +        cfg_file - name or path and name of cfg file for parsing
As you know in cfg file value can be any type. So function can bring different types of data.

2017-05-20 12:35 UTC, RomanPryima commented on config_parser/config_reader.py
> +        The return value. The value of requested parameter in requested
What I can write here if it returns exactly that?

2017-05-23 11:35 UTC, RomanPryima commented on config_parser/config_reader.py
> +def get_setting(cfg_file, section,  parameter):
fixed

2017-05-23 12:55 UTC, pivancy commented on config_parser/config_reader.py
> +        The return value. The value of requested parameter in requested
What is `that`? It's not clear from your sentence "Returns the return value."

2017-05-23 17:47 UTC, RomanPryima commented on config_parser/config_reader.py
> +        The return value. The value of requested parameter in requested
corrected

2017-05-23 17:47 UTC, RomanPryima commented on config_parser/config_reader.py
> +        cfg_file - name or path and name of cfg file for parsing
corrected

2017-05-23 19:58 UTC, UkrainianEngineer requested changes

2017-05-23 19:58 UTC, pivancy commented on config_parser/config_reader.py
> +        string: The value of requested parameter in requested
`str` not `string`.

2017-05-24 04:14 UTC, RomanPryima commented on config_parser/config_reader.py
> +        string: The value of requested parameter in requested
corrected

2017-05-24 07:00 UTC, UkrainianEngineer requested changes

2017-05-24 07:00 UTC, pivancy commented on config_parser/config_reader.py
> +def get_setting(cfg_file, section,  parameter):
Are you sure that it's fixed? I don't think so.

2017-05-24 10:40 UTC, RomanPryima commented on config_parser/config_reader.py
> +def get_setting(cfg_file, section,  parameter):
Now it surely done.

2017-05-24 11:22 UTC, pivancy commented
LGTM, :+1:

2017-05-24 11:22 UTC, UkrainianEngineer approved these changes

2017-05-24 12:15 UTC, kate-ka approved these changes
👍

2017-05-24 13:50 UTC, Sasha1152 commented
:+1:

2017-05-24 13:55 UTC, Sasha1152 approved these changes
:+1:  :+1:  :+1:

2017-05-24 17:21 UTC, merged