26 get real data from izi travel api using our custom python wrapper
pivancy/itea-advanced-python pull request #26
Opened 2017-06-01 07:35 UTC by kate-ka

2017-06-01 14:44 UTC, pivancy commented on travel_platform/izi_travel_client.py
> +import os
It would be great to add some folder like `api` and add all our APIs functionalities into this.

2017-06-02 20:51 UTC, UkrainianEngineer requested changes

2017-06-02 20:51 UTC, pivancy commented on travel_platform/izitravel_data_tests.py
> +from izitravel_data import find_city_tours, find_museums,\
It's much better to use this type of multiline imports:
```
from something import (one, two, three,
    four, five, six
)
```

2017-06-02 20:51 UTC, pivancy commented on travel_platform/izi_travel_client.py
> +import os
I suggest to rename all appropriate files into `izi_travel_` instead of `izitravel_`.

2017-06-06 08:31 UTC, kate-ka commented on travel_platform/izi_travel_client.py
> +import os
Added

2017-06-06 08:31 UTC, kate-ka commented on travel_platform/izi_travel_client.py
> +import os
Done

2017-06-06 08:31 UTC, kate-ka commented on travel_platform/izi_travel_client.py
> +import os
Done

2017-06-06 08:32 UTC, kate-ka commented on travel_platform/izitravel_data_tests.py
> +from izitravel_data import find_city_tours, find_museums,\
Done

2017-06-07 11:56 UTC, UkrainianEngineer approved these changes

2017-06-07 11:56 UTC, pivancy commented
:+1:

2017-06-07 11:56 UTC, pivancy commented
:+1:

2017-06-07 12:07 UTC, Sasha1152 commented
:+1:

2017-06-11 06:35 UTC, kate-ka commented
@RomanPryima What about you? Do you approve this pr?)

2017-06-11 10:21 UTC, merged