ITEA-29-make-view-getting-name-of-location-by-the-coordinates-received-from-the-frontend
pivancy/itea-advanced-python pull request #35
Opened 2017-06-15 13:08 UTC by RomanPryima

2017-06-15 13:48 UTC, kate-ka commented on travel_platform/travel_app/views.py
> +    api_key = 'lrGqjWqt82ZGMvQPA0SPXqctacNvptot'
Btw, I know one more convenient url for reverse geocoding, no api key needed: `http://nominatim.openstreetmap.org/reverse?format=json&lat=49.863280&lon=24.031760&zoom=18&addressdetails=1`

2017-06-15 14:52 UTC, pivancy commented on travel_platform/travel_app/views.py
> +    api_url = 'http://open.mapquestapi.com/geocoding/v1/reverse'
This data should be located in configuration file.

2017-06-15 14:52 UTC, pivancy commented on travel_platform/travel_app/views.py
> +    api_key = 'lrGqjWqt82ZGMvQPA0SPXqctacNvptot'
@RomanPryima , did you have a chance to check suggested resource?

2017-06-15 14:52 UTC, pivancy commented on travel_platform/travel_app/views.py
> +    location_request = requests.get(str(api_url + '?key=' + api_key +
It looks too complicated.
Can't it be done in simpler way?

2017-06-15 14:52 UTC, pivancy commented on travel_platform/travel_app/views.py
> +    response = str(location_data['results'][0]['locations'][0]['adminArea5'])
What is the result of this?

2017-06-15 16:23 UTC, RomanPryima commented on travel_platform/travel_app/views.py
> +    response = str(location_data['results'][0]['locations'][0]['adminArea5'])
Name of the city parsed from API response.

2017-06-15 16:24 UTC, RomanPryima commented on travel_platform/travel_app/views.py
> +    api_key = 'lrGqjWqt82ZGMvQPA0SPXqctacNvptot'
Yes. It works.
Is there a reason to change API?

2017-06-15 16:25 UTC, RomanPryima commented on travel_platform/travel_app/views.py
> +    api_url = 'http://open.mapquestapi.com/geocoding/v1/reverse'
It is described as task in TO DO comment

2017-06-18 14:30 UTC, UkrainianEngineer commented on travel_platform/travel_app/views.py
> +    # TO DO RomanPryima: move url and api key into cfg file and make view
Use `TODO` instead of `TO DO`.

2017-06-19 14:05 UTC, RomanPryima commented on travel_platform/travel_app/views.py
> +    # TO DO RomanPryima: move url and api key into cfg file and make view
ok

2017-06-19 18:40 UTC, RomanPryima commented
@pivancy Take a look, please, why the section "api.open.map" in configuration.cfg file, can't be reached from views.py with config_reader.py.
The error appears when user click on map.

2017-06-20 12:16 UTC, UkrainianEngineer requested changes

2017-06-20 12:16 UTC, pivancy commented on travel_platform/travel_app/config/conf.py
> +print(CONF_PATH)
Do you really need this print?

2017-06-20 12:16 UTC, pivancy commented on travel_platform/travel_app/views.py
> +sys.path.append('../../config_parser')
This looks terrible..

2017-06-20 12:16 UTC, pivancy commented on travel_platform/travel_app/views.py
> +    # api_url = 'http://open.mapquestapi.com/geocoding/v1/reverse'
Do we really need these commented lines here?

2017-06-20 12:16 UTC, pivancy commented on travel_platform/travel_app/views.py
> +    conf_path = './config/configurations.cfg'
Hard-coded path here?

2017-06-20 12:16 UTC, pivancy commented on travel_platform/travel_app/views.py
> +    location = str(','.join([coordinate_lat, coordinate_lon]))
What is the reason of this?
AFAIK, ```','.join([1,2])``` always returns `str` type. Isn't it?

2017-06-20 12:16 UTC, pivancy commented on travel_platform/travel_app/views.py
> +    response = str(response.encode('utf-8'))
What is the original type of `response.encode('utf-8')`?

2017-06-20 12:27 UTC, RomanPryima commented on travel_platform/travel_app/config/conf.py
> +print(CONF_PATH)
deleted. Was necessary during corecting file

2017-06-20 12:27 UTC, RomanPryima commented on travel_platform/travel_app/views.py
> +    conf_path = './config/configurations.cfg'
fixed

2017-06-20 12:27 UTC, RomanPryima commented on travel_platform/travel_app/views.py
> +sys.path.append('../../config_parser')
corrected

2017-06-20 12:28 UTC, RomanPryima commented on travel_platform/travel_app/views.py
> +    # api_url = 'http://open.mapquestapi.com/geocoding/v1/reverse'
deleted

2017-06-20 12:30 UTC, RomanPryima commented on travel_platform/travel_app/views.py
> +    location = str(','.join([coordinate_lat, coordinate_lon]))
fixed

2017-06-20 12:31 UTC, RomanPryima commented on travel_platform/travel_app/views.py
> +    response = str(response.encode('utf-8'))
string.
corrected.

2017-06-20 14:29 UTC, pivancy commented on config_parser/conf_reader_test.py
> +        pass
What is the reason of this `setUp` method?

2017-06-20 14:29 UTC, pivancy commented on travel_platform/travel_app/views.py
> +sys.path.append('../../config_parser/')
Omg..
Add `FIXME` to refactor this part of code.

2017-06-20 14:29 UTC, pivancy commented on travel_platform/travel_app/views.py
> +    response = location_data['results'][0]['locations'][0]['adminArea5']
Well, can't it be replaced with `get` methods?

2017-06-20 14:51 UTC, RomanPryima commented on travel_platform/travel_app/views.py
> +    response = location_data['results'][0]['locations'][0]['adminArea5']
I didn't find easier method, because there is a mix with tuples and lists enclosed into each other. But it has stable immutable structure.

2017-06-20 14:52 UTC, RomanPryima commented on travel_platform/travel_app/views.py
> +sys.path.append('../../config_parser/')
I have no idea how to add new sys path without adding it.

2017-06-20 16:38 UTC, RomanPryima commented on config_parser/conf_reader_test.py
> +        pass
deleted

2017-06-21 04:15 UTC, RomanPryima commented on travel_platform/travel_app/views.py
> +sys.path.append('../../config_parser/')
Added FIXME comment

2017-06-22 11:31 UTC, Sasha1152 commented
:+1:  God job!

2017-06-22 13:09 UTC, kate-ka approved these changes
Well done! 👍

2017-06-22 13:17 UTC, UkrainianEngineer approved these changes

2017-06-22 13:17 UTC, pivancy commented
:+1: 
Btw, There is one question without your response.

2017-06-22 13:25 UTC, RomanPryima commented on travel_platform/travel_app/views.py
> +    location_request = requests.get(str(api_url + '?key=' + api_key +
Remade

2017-06-22 13:26 UTC, RomanPryima commented
@pivancy  Responsed

2017-06-22 14:39 UTC, merged